APP_NAME = "qbit-quick"
DATABASE_FILENAME = "race.sqlite"
TOO_MANY_REQUESTS_DELAY = 10

# Environment variables
QBQ_LOGS_DIR = "QBQ_LOGS_DIR"
QBQ_CONFIG_DIR = "QBQ_CONFIG_DIR"
QBQ_STATE_DIR = "QBQ_STATE_DIR"
